services:
  app:
    build:
      context: .  # El contexto es la raíz del proyecto
      dockerfile: Dockerfile  # Nombre del Dockerfile que se encuentra en la raíz
    container_name: back-sv-admin  # Nombre del contenedor
    ports:
      - "8090:8090"  # Exponer el puerto 8090 de la aplicación
    environment:
      SPRING_PROFILES_ACTIVE: ${ENVIRONMENT}  # Activar el perfil de producción (o test)
    env_file:  # Cargar variables de entorno desde el archivo .env
      - .env
    restart: always  # Reiniciar siempre que sea necesario
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"  # Mapea el puerto 8080 del contenedor al 8081 en el host
    restart: unless-stopped  # Reiniciar a menos que se detenga manualmente
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
