services:
  app:
    build:
      context: .
    container_name: springboot_app
    ports:
      - "8090:8090"  # Puerto expuesto para la aplicación
    environment:
      SPRING_PROFILES_ACTIVE: prod  # Activar el perfil de producción (o test)
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/innovatech
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: innovatech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin      # Clave de acceso (Access Key)
      MINIO_ROOT_PASSWORD: minioadminpassword  # Clave secreta (Secret Key)
    volumes:
      - ./data:/data                   # Mapea el almacenamiento en tu máquina local
    ports:
      - "9000:9000"                    # Puerto para la API de MinIO
      - "9001:9001"                    # Puerto para la consola de administración
    restart: always                    # Reiniciar el contenedor automáticamente
    command: server /data --console-address ":9001"

volumes:
  db_data: