name: Deploy SpringBoot App to Testing

on:
  workflow_run:
    workflows: ["TestDeployment"]  # Se activa cuando el workflow 'TestDeployment' se completa
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, test-admin]  # Runner local para 'testing'

    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Solo ejecuta si 'TestDeployment' fue exitoso

    steps:
    - name: Comprobando el repositorio
      uses: actions/checkout@v4

    - name: Configurar el agente SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY_TESTING }}

    - name: Ejecutar el script de despliegue
      run: |
        ssh -o StrictHostKeyChecking=no estudiante@10.43.100.236 'bash -s' < ./deploy.sh testing
      working-directory: ./  # Establece el directorio de trabajo a la raíz del repositorio

    - name: Comprobar estado de despliegue
      run: |
        ssh -o StrictHostKeyChecking=no estudiante@10.43.100.236 'docker ps'
