name: CI Java maven

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17' 

      - name: Build with Maven
        run: |
          cd back-admin  # Correct directory with pom.xml
          mvn clean install

      - name: Run tests
        run: |
          cd back-admin  # Ensure you're in the correct directory
          mvn test

  auto-merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Merge pull request
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout dev
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin dev
