name: CI Workflow

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: |
          cd demo
          mvn clean install

      - name: Run tests
        run: |
          cd demo
          mvn test

  merge:
    needs: build  # Solo se ejecuta si 'build' pasa exitosamente
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' && github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev' }}  # Condición de éxito

    steps:
      - name: Attempt to merge pull request
        run: |
          response=$(curl -s -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"commit_title": "Automated merge from CI", "merge_method": "merge"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge")
          echo "$response"
          if echo "$response" | grep -q "already merged" || echo "$response" | grep -q "already up to date"; then
            echo "Pull request already merged or up to date, skipping merge."
            exit 0
          elif echo "$response" | grep -q "Merge conflict"; then
            echo "Merge conflict detected!" && exit 1
          fi

  reject:
    needs: build  # Solo se ejecuta si 'build' falla
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'failure' && github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev' }}  # Condición de fallo
    
    steps:
      - name: Close pull request on failure
        run: |
          curl -s -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"state": "closed"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
