name: CI feat to dev

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'  # Cambia según la versión que uses

      - name: Build with Maven
         run: |
          cd back-admin/demo  # Cambia al directorio correcto
          mvn clean install

      - name: Run tests
        run: mvn test

  auto-merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Merge pull request
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout dev
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin dev
